import {defineField, defineType} from 'sanity'

/** Bullet block under a heading (e.g. workshop requirements). */
export const gtp2026SubmissionsRichSectionType = defineType({
  name: 'gtp2026SubmissionsRichSection',
  title: 'Rich subsection',
  type: 'object',
  fields: [
    defineField({name: 'title', title: 'Heading', type: 'string'}),
    defineField({
      name: 'intro',
      title: 'Intro paragraph (optional)',
      type: 'text',
      rows: 3,
    }),
    defineField({
      name: 'bullets',
      title: 'Bullet lines',
      type: 'array',
      of: [{type: 'string'}],
    }),
    defineField({
      name: 'footer',
      title: 'Footer note (optional)',
      type: 'text',
      rows: 2,
    }),
  ],
})

export const gtp2026SubmissionsEvalCriterionGroupType = defineType({
  name: 'gtp2026SubmissionsEvalCriterionGroup',
  title: 'Evaluation criterion group',
  type: 'object',
  fields: [
    defineField({name: 'title', title: 'Group title', type: 'string'}),
    defineField({
      name: 'items',
      title: 'Criteria (one per line)',
      type: 'array',
      of: [{type: 'string'}],
    }),
  ],
})

export const gtp2026AbstractFormCopyType = defineType({
  name: 'gtp2026AbstractFormCopy',
  title: 'Abstract submission form copy',
  type: 'object',
  options: {collapsible: true, collapsed: true},
  fields: [
    defineField({name: 'headerTitle', title: 'Header — conference title', type: 'string'}),
    defineField({name: 'headerSubtitle', title: 'Header — form title', type: 'string'}),
    defineField({name: 'introParagraph1', title: 'Intro paragraph 1', type: 'text', rows: 4}),
    defineField({name: 'introParagraph2', title: 'Intro paragraph 2', type: 'text', rows: 4}),
    defineField({name: 'guidelinesTitle', title: 'Guidelines callout — title', type: 'string'}),
    defineField({
      name: 'guidelinesBullets',
      title: 'Guidelines — bullet lines',
      type: 'array',
      of: [{type: 'string'}],
    }),
    defineField({name: 'importantDatesTitle', title: 'Important dates — title', type: 'string'}),
    defineField({
      name: 'importantDatesBullets',
      title: 'Important dates — bullet lines',
      type: 'array',
      of: [{type: 'string'}],
    }),
    defineField({
      name: 'contactLead',
      title: 'Contact line — before email (plain text)',
      type: 'text',
      rows: 2,
    }),
    defineField({name: 'contactEmail', title: 'Contact email (address only)', type: 'string'}),
    defineField({
      name: 'contactMailtoSubject',
      title: 'mailto: subject parameter',
      type: 'string',
    }),
    defineField({
      name: 'contactSubjectEmphasis',
      title: 'Subject line shown in italics after the link',
      type: 'string',
    }),
    defineField({
      name: 'presentingAuthorNote',
      title: 'Note under contact (presenting author)',
      type: 'text',
      rows: 2,
    }),
    defineField({name: 'sectionPresenterDetails', title: 'Section — Presenter details', type: 'string'}),
    defineField({name: 'sectionSubmissionDetails', title: 'Section — Submission details', type: 'string'}),
    defineField({name: 'labelEmail', title: 'Label — Email', type: 'string'}),
    defineField({name: 'labelFullName', title: 'Label — Full name', type: 'string'}),
    defineField({name: 'labelInstitution', title: 'Label — Institution', type: 'string'}),
    defineField({name: 'labelDesignation', title: 'Label — Designation', type: 'string'}),
    defineField({
      name: 'designationPlaceholder',
      title: 'Placeholder — Designation',
      type: 'string',
    }),
    defineField({name: 'labelCountry', title: 'Label — Country', type: 'string'}),
    defineField({
      name: 'labelEarlyCareerQuestion',
      title: 'Label — Early career question',
      type: 'text',
      rows: 2,
    }),
    defineField({name: 'earlyCareerYesLabel', title: 'Early career — Yes option', type: 'string'}),
    defineField({name: 'earlyCareerNoLabel', title: 'Early career — No option', type: 'string'}),
    defineField({name: 'labelPrimaryTheme', title: 'Label — Primary theme', type: 'string'}),
    defineField({
      name: 'labelPresentationPreference',
      title: 'Label — Presentation preference',
      type: 'string',
    }),
    defineField({name: 'presentationOralLabel', title: 'Presentation — Oral', type: 'string'}),
    defineField({name: 'presentationPosterLabel', title: 'Presentation — Poster', type: 'string'}),
    defineField({name: 'labelAbstractTitle', title: 'Label — Abstract title', type: 'string'}),
    defineField({
      name: 'placeholderAbstractTitle',
      title: 'Placeholder — Abstract title',
      type: 'string',
    }),
    defineField({
      name: 'abstractTitleMaxWords',
      title: 'Max words — abstract title',
      type: 'number',
    }),
    defineField({name: 'labelAbstract', title: 'Label — Abstract body', type: 'string'}),
    defineField({
      name: 'helperAbstract',
      title: 'Helper — Abstract body',
      type: 'text',
      rows: 2,
    }),
    defineField({
      name: 'placeholderAbstract',
      title: 'Placeholder — Abstract body',
      type: 'string',
    }),
    defineField({
      name: 'abstractBodyMaxWords',
      title: 'Max words — abstract body',
      type: 'number',
    }),
    defineField({name: 'labelAuthorList', title: 'Label — Author list', type: 'string'}),
    defineField({
      name: 'placeholderAuthorList',
      title: 'Placeholder — Author list',
      type: 'string',
    }),
    defineField({
      name: 'wordCountLimitReachedSuffix',
      title: 'Word count — “limit reached” suffix',
      type: 'string',
      description: 'Appended when max words hit, e.g. " — limit reached"',
    }),
    defineField({name: 'submitButtonIdle', title: 'Submit button — idle label', type: 'string'}),
    defineField({
      name: 'submitButtonSubmitting',
      title: 'Submit button — submitting label',
      type: 'string',
    }),
    defineField({
      name: 'overlaySubmittingLabel',
      title: 'Full-page overlay — submitting',
      type: 'string',
    }),
    defineField({
      name: 'successSnackbarMessage',
      title: 'Success snackbar message',
      type: 'text',
      rows: 2,
    }),
    defineField({
      name: 'fieldGenericPlaceholder',
      title: 'Generic field placeholder',
      type: 'string',
      description: 'Fallback when a field has no specific placeholder.',
    }),
  ],
})

export const gtp2026WorkshopFormCopyType = defineType({
  name: 'gtp2026WorkshopFormCopy',
  title: 'Workshop proposal form copy',
  type: 'object',
  options: {collapsible: true, collapsed: true},
  fields: [
    defineField({name: 'headerTitle', title: 'Header — conference title', type: 'string'}),
    defineField({name: 'headerSubtitle', title: 'Header — form title', type: 'string'}),
    defineField({name: 'introParagraph1', title: 'Intro paragraph 1', type: 'text', rows: 4}),
    defineField({name: 'introParagraph2', title: 'Intro paragraph 2', type: 'text', rows: 4}),
    defineField({name: 'introParagraph3', title: 'Intro paragraph 3', type: 'text', rows: 4}),
    defineField({
      name: 'pillarsThemesCalloutTitle',
      title: 'Teal callout — title',
      type: 'text',
      rows: 2,
    }),
    defineField({
      name: 'requirementsPanelTitle',
      title: 'Collapsible panel — button title',
      type: 'string',
    }),
    defineField({
      name: 'requirementsSections',
      title: 'Requirements — subsections',
      type: 'array',
      of: [{type: 'gtp2026SubmissionsRichSection'}],
    }),
    defineField({
      name: 'evaluationCriteriaTitle',
      title: 'Evaluation — section title',
      type: 'string',
    }),
    defineField({
      name: 'evaluationGroups',
      title: 'Evaluation — criterion groups',
      type: 'array',
      of: [{type: 'gtp2026SubmissionsEvalCriterionGroup'}],
    }),
    defineField({name: 'importantDatesTitle', title: 'Important dates — title', type: 'string'}),
    defineField({
      name: 'importantDatesBullets',
      title: 'Important dates — bullet lines',
      type: 'array',
      of: [{type: 'string'}],
    }),
    defineField({
      name: 'contactLead',
      title: 'Contact line — before email',
      type: 'text',
      rows: 2,
    }),
    defineField({name: 'contactEmail', title: 'Contact email', type: 'string'}),
    defineField({name: 'contactMailtoSubject', title: 'mailto: subject', type: 'string'}),
    defineField({
      name: 'contactSubjectEmphasis',
      title: 'Subject line (italics)',
      type: 'string',
    }),
    defineField({name: 'registrationFeeNote', title: 'Registration fee note', type: 'text', rows: 2}),
    defineField({name: 'sectionConvenerDetails', title: 'Section — Convener details', type: 'string'}),
    defineField({name: 'sectionSessionOverview', title: 'Section — Session overview', type: 'string'}),
    defineField({name: 'sectionSessionOutline', title: 'Section — Session outline', type: 'string'}),
    defineField({
      name: 'sectionResourceRequirements',
      title: 'Section — Resource requirements',
      type: 'string',
    }),
    defineField({
      name: 'sectionDeclaration',
      title: 'Section — Declaration',
      type: 'string',
    }),
    defineField({name: 'labelEmail', title: 'Label — Email', type: 'string'}),
    defineField({name: 'labelFullName', title: 'Label — Full name', type: 'string'}),
    defineField({
      name: 'labelInstitution',
      title: 'Label — Institution / organisation',
      type: 'string',
    }),
    defineField({name: 'labelDesignation', title: 'Label — Designation', type: 'string'}),
    defineField({
      name: 'designationPlaceholder',
      title: 'Placeholder — Designation',
      type: 'string',
    }),
    defineField({name: 'labelCountry', title: 'Label — Country', type: 'string'}),
    defineField({
      name: 'labelProposedSessionTitle',
      title: 'Label — Proposed session title',
      type: 'string',
    }),
    defineField({
      name: 'placeholderSessionTitle',
      title: 'Placeholder — Session title',
      type: 'string',
    }),
    defineField({
      name: 'sessionTitleMaxWords',
      title: 'Max words — session title',
      type: 'number',
    }),
    defineField({
      name: 'labelPrimaryPillar',
      title: 'Label — Primary conference pillar',
      type: 'string',
    }),
    defineField({
      name: 'primaryPillarOptions',
      title: 'Primary pillar options (values submitted to server)',
      type: 'array',
      of: [{type: 'string'}],
      validation: (rule) => rule.max(8),
    }),
    defineField({
      name: 'labelPrimaryThematicArea',
      title: 'Label — Primary thematic area',
      type: 'string',
    }),
    defineField({
      name: 'labelSecondaryThemes',
      title: 'Label — Secondary themes (legend)',
      type: 'text',
      rows: 2,
    }),
    defineField({
      name: 'secondaryThemesHint',
      title: 'Secondary themes — hint in parentheses',
      type: 'string',
    }),
    defineField({
      name: 'secondaryThemesPrimaryBadge',
      title: 'Secondary themes — “Primary” badge',
      type: 'string',
    }),
    defineField({
      name: 'secondaryThemesMaxSelectedNote',
      title: 'Secondary themes — max selected message',
      type: 'string',
    }),
    defineField({
      name: 'labelSessionObjectives',
      title: 'Label — Session objectives',
      type: 'string',
    }),
    defineField({
      name: 'placeholderSessionObjectives',
      title: 'Placeholder — Session objectives',
      type: 'string',
    }),
    defineField({
      name: 'labelExpectedOutcomes',
      title: 'Label — Expected outcomes',
      type: 'string',
    }),
    defineField({
      name: 'helperExpectedOutcomes',
      title: 'Helper — Expected outcomes',
      type: 'text',
      rows: 3,
    }),
    defineField({
      name: 'labelSessionDetails',
      title: 'Label — Session details',
      type: 'string',
    }),
    defineField({
      name: 'helperSessionDetails',
      title: 'Helper — Session details',
      type: 'text',
      rows: 6,
    }),
    defineField({
      name: 'labelSpeakerList',
      title: 'Label — Speaker / facilitator list',
      type: 'string',
    }),
    defineField({
      name: 'helperSpeakerList',
      title: 'Helper — Speaker list',
      type: 'text',
      rows: 5,
    }),
    defineField({
      name: 'labelResourceRequirements',
      title: 'Label — Technical / venue requirements',
      type: 'string',
    }),
    defineField({
      name: 'helperResourceRequirements',
      title: 'Helper — Resource requirements',
      type: 'text',
      rows: 5,
    }),
    defineField({
      name: 'labelFinancialResources',
      title: 'Label — Financial resources question',
      type: 'text',
      rows: 3,
    }),
    defineField({name: 'financialOptionYes', title: 'Financial — Yes', type: 'string'}),
    defineField({name: 'financialOptionNo', title: 'Financial — No', type: 'string'}),
    defineField({
      name: 'financialOptionUncertain',
      title: 'Financial — Uncertain',
      type: 'string',
    }),
    defineField({
      name: 'labelDiversityStatement',
      title: 'Label — Diversity statement',
      type: 'string',
    }),
    defineField({
      name: 'placeholderDiversityStatement',
      title: 'Placeholder — Diversity statement',
      type: 'string',
    }),
    defineField({
      name: 'labelConflictOfInterest',
      title: 'Label — Conflict of interest',
      type: 'string',
    }),
    defineField({
      name: 'conflictIntro',
      title: 'Conflict — intro paragraph',
      type: 'text',
      rows: 3,
    }),
    defineField({
      name: 'conflictOptionNoConflicts',
      title: 'Conflict — option: no conflicts',
      type: 'string',
    }),
    defineField({
      name: 'conflictOptionHasConflicts',
      title: 'Conflict — option: has conflicts',
      type: 'string',
    }),
    defineField({
      name: 'labelConflictDetails',
      title: 'Label — Specify conflicts',
      type: 'string',
    }),
    defineField({
      name: 'placeholderConflictDetails',
      title: 'Placeholder — Conflict details',
      type: 'string',
    }),
    defineField({name: 'submitButtonIdle', title: 'Submit button — idle', type: 'string'}),
    defineField({
      name: 'submitButtonSubmitting',
      title: 'Submit button — submitting',
      type: 'string',
    }),
    defineField({
      name: 'overlaySubmittingLabel',
      title: 'Overlay — submitting',
      type: 'string',
    }),
    defineField({
      name: 'successSnackbarMessage',
      title: 'Success snackbar',
      type: 'text',
      rows: 2,
    }),
    defineField({
      name: 'fieldGenericPlaceholder',
      title: 'Generic placeholder',
      type: 'string',
    }),
    defineField({
      name: 'wordCountLimitReachedSuffix',
      title: 'Word count — “limit reached” suffix',
      type: 'string',
    }),
  ],
})
